### ISSUE TITLE
Where does c-for-go search for dependencies? 

### ISSUE THREAD

**Issue by dh1tw** [xlab/c-for-go#17]
Hi, 

I was trying to generate the opus binding from your example repository. However on both, my Mac and the Linux machine, the process aborts with the message: 

```
[ERR] /usr/include/features.h:367:12: include file not found: sys/cdefs.h (and 3 more errors)
```

Where does c-for-go exactly search for the dependencies?

**Comment by xlab** [comment]
@dh1tw 
This is very strange, because it works for me as always on mac..
It searches for defines as in manifest: https://github.com/xlab/opus-go/blob/master/opus.yml#L10

P.S. I don't have `/usr/include/features.h` on my 10.12.1 and my mac is a working horse in terms of cross-compilation and strange stuff I'm building and installing. It think you accidentally cluttered your `/usr/include` or something like that.

P.S.S. try running `c-for-go -ccincl`

**Comment by dh1tw** [comment]
bingo - `$ c-for-go -ccincl` did the trick! Both, on the Mac and on the Linux machine.

**Comment by xlab** [comment]
To clarify: this flag invokes a host-based CPP executable and gets its environment, for this case — sys include paths to use in addition to `/usr/include`. Normally you won't do that, but in your case it's needed. First time I see this ;)
